{{- define "common.vaultStaticSecret.tpl" -}}
{{- $robustName := include "common.robustName" $.Release.Name }}
{{- if .Values.vaultStaticSecret }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $robustName }}
  namespace: {{ $.Release.Namespace }}
spec:
{{- with .Values.vaultStaticSecret }}
  type: {{ .type | default "kv-v2" }}
  mount: {{ .mount | default "secret" }}
  path: {{ .secretPath }}
  destination:
    name: {{ $robustName }}
    create: true
  refreshAfter: {{ .refreshAfter | default "30s" }}
  vaultAuthRef: {{ .vaultAuthRef | default "default" }}
{{- end }}
{{- end }}
{{- end }}